### ISSUE TITLE
Publish ADFCustomActivityDebugger as a nuget package

### ISSUE THREAD

**Issue by drorkremer** [gbrueckl/Azure.DataFactory.CustomActivityDebugger#2]
It'd be easier to consume the functionality from the ADFCustomActivityDebugger class if it was published as a nuget package instead of polling the sources on github :)

**Comment by gbrueckl** [comment]
thanks for the suggestion, 
I will definitely look into this for the future releases
-gerhard

**Comment by gbrueckl** [comment]
re-created this issue in https://github.com/gbrueckl/Azure.DataFactory.LocalEnvironment which is the newer version with extended features (ARM-export, ...)
